### ISSUE TITLE
url 인코딩

### ISSUE THREAD

**Issue by kyY00n** [plzprayme/online-judge-directory-tree-to-readme#1]
(왠지 아시면서 안하고 계신거같은,..)
파일 이름에 띄어쓰기했더니  링크가 저렇게 됐어요 고쳐쥬세요 성찬님

<img width="785" alt="image" src="https://user-images.githubusercontent.com/61582017/193104922-2632c5fb-d996-4bd6-917f-28a3b2a37f7f.png">

https://github.com/plzprayme/online-judge-directory-tree-to-readme/blob/9fb7b1fa4eab6286f6812955760a6f7bd77d4c58/src/main/java/makrdown/MarkdownBuilder.java#L26

**Comment by plzprayme** [comment]
저의 벌레 코드를 훔쳐보셨군요. 훔쳐본 대가는 직접 수정해서 PR을 날리는겁니다.

첨부해주신 커밋버전은 폴더명 정렬이 안되어서 버렸구용. 
[https://github.com/plzprayme/online-judge-directory-tree-to-readme/tree/application](https://github.com/plzprayme/online-judge-directory-tree-to-readme/tree/application) 여기에 더 지옥같은 코드가 기다리고 있습니다. 이 코드가 실제로 코테 레포에서 동작하고 있어요. 

한번 수정 해보실?

**Comment by plzprayme** [comment]
알고 있는데 작업 안한 이유는 띄어쓰기 말고도 또 인코딩이 깨지는 문자가 있지 않을까 싶어서 작업 방법을 고민하고 있었어요.

**Comment by kyY00n** [comment]
@plzprayme ㅋㅋㅋㅋㅋ 지옥...코드ㅋㅋ 저는 저 줄만 보고 만든 url 통째로 URLEncoder로 변환해주면 될 거라 생각했는데, 또 다른 문제가 있을지 함 봐야겠녜요

**Comment by plzprayme** [comment]
감사합니당
